# Generated by Django 2.1.5 on 2019-02-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myama',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jinsia', models.CharField(choices=[('DUME', 'Male'), ('JIKE', 'Female')], max_length=5)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amesejiliwa_serikalini', models.BooleanField(default=False)),
                ('rangi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('initial_status', models.CharField(choices=[('AMENUNULIWA', 'Amenunuliwa'), ('AMEZALIWA', 'Amezaliwa'), ('HAIJULIKANI', 'Haijulikani')], default='HAIJULIKANI', max_length=25)),
                ('initial_status_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('MZIMA', 'Mzima'), ('AMEKUFA', 'Amekufa'), ('AMEUUZWA', 'Ameuzwa'), ('AMECHINJWA', 'Amechinjwa'), ('HAIJULIKANI', 'Haijulikani'), ('AMEPOTEA', 'Amepotea')], default='HAIJULIKANI', max_length=25)),
                ('current_status_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shamba',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jina', models.TextField(blank=True, db_index=True)),
                ('jina_fupi', models.TextField(blank=True, db_index=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kondo',
            fields=[
                ('myama_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mifugo.Myama')),
                ('breed', models.CharField(choices=[('BHP', 'Black Head Persian'), ('OTHER', 'Other')], max_length=25)),
                ('baba', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kondo_baba', to='mifugo.Kondo')),
                ('mama', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kondo_mama', to='mifugo.Kondo')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('mifugo.myama',),
        ),
        migrations.CreateModel(
            name='Mbuzi',
            fields=[
                ('myama_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mifugo.Myama')),
                ('breed', models.CharField(choices=[('BOER', 'boer'), ('OTHER', 'Other')], max_length=25)),
                ('baba', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mbuzi_baba', to='mifugo.Mbuzi')),
                ('mama', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mbuzi_mama', to='mifugo.Mbuzi')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('mifugo.myama',),
        ),
        migrations.CreateModel(
            name='Ngombe',
            fields=[
                ('myama_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mifugo.Myama')),
                ('breed', models.CharField(choices=[('ANKOLE', 'Ankole'), ('AYRSHIRE', 'Ayrshire'), ('JERSEY', 'Jersey'), ('FRIESIAN', 'Friesian'), ('OTHER', 'Other')], max_length=25)),
                ('baba', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ngombe_baba', to='mifugo.Ngombe')),
                ('mama', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ngombe_mama', to='mifugo.Ngombe')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('mifugo.myama',),
        ),
        migrations.AddField(
            model_name='myama',
            name='breeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='breeder', to='mifugo.Shamba'),
        ),
        migrations.AddField(
            model_name='myama',
            name='shamba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mifugo.Shamba'),
        ),
    ]
